# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1urluoiqOp9gg9JXONLQc3DtBDcHovkdV
"""

import pandas as pd
data = pd.read_csv('/content/materias - materias.csv', header=None)
datos = pd.read_csv('materias - materias.csv')

data.head(2) >

data.tail(1)

df1 = pd.DataFrame(datos)
print(df1)

datos_filtrados = df1['Materias Desaprobadas']<2
print(datos_filtrados)

df1[datos_filtrados]

datos_filtrados = df1['Materias Previas']==0
print(datos_filtrados)

df1[datos_filtrados]